name: Update Container

on:
  push:
    branches: [dev]
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Update Container
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: actions/checkout@v3
      - run: pwd && ls && node -v
      - run: yarn
      - run: yarn build
      - run: docker build -t sufuwang/ylwawj-fe -f ./nginx.dockerfile .
      - run: docker images ps
      - run: docker push sufuwang/ylwawj-fe

      - name: Update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: sudo groupadd docker && sudo usermod -aG docker $USER && newgrp docker && docker rm -f ylwawj-fe && docker pull sufuwang/ylwawj-fe && docker run -d -p 80:80 --name ylwawj-fe --rm sufuwang/ylwawj-fe
